# [build]
# build-std = false                              # do not build the std library. has precedence over xargo
# xargo = true                                   # enable the use of xargo by default
# zig = false                                    # do not use zig cc for the builds
# # default-target = "aarch64-unknown-linux-gnu"    # use this target if none is explicitly provided 
# pre-build = [
# #   "dpkg --add-architecture $CROSS_DEB_ARCH", 
# #   "apt-get update && apt-get --assume-yes install libssl-dev:$CROSS_DEB_ARCH"
# ]
# dockerfile = "./Dockerfile"

[package.metadata.cross.target.x86_64-unknown-linux-musl]
xargo = false
image = "togettoyou/ghcr.io.cross-rs.x86_64-unknown-linux-musl"

[package.metadata.cross.target.aarch64-linux-android]
xargo = false
image = "togettoyou/ghcr.io.cross-rs.aarch64-linux-android"


